#!/bin/sh
#
# This script will download NodeJS, NPM and lessc, and install them into you Python
# virtualenv.
#
# Based on a post by Natim:
# http://stackoverflow.com/questions/8986709/how-to-install-lessc-and-nodejs-in-a-python-virtualenv

VERSION=v0.8.8
NODEJS="http://nodejs.org/dist/$VERSION/node-$VERSION.tar.gz"

# Check dependencies
for dep in gcc wget curl tar make; do
	which $dep > /dev/null || (echo "ERROR: $dep not found"; exit 10)
done

# Must be run from virtual env
if [ "$VIRTUAL_ENV" = "" ]; then
	echo "ERROR: you must activate the virtualenv first!"
	exit 1
fi

echo "1) Installing nodejs in current virtual env"
echo

cd "$VIRTUAL_ENV"


# Check node is exists or not
which node>/dev/null 2>/dev/null
if [ $? -eq 0 ]; then
    echo "The node-js is installed."
else
    # Create temp dir
    if [ ! -d "tmp" ]; then
        mkdir tmp
    fi
    cd tmp || (echo "ERROR: entering tmp directory failed"; exit 4)

    echo -n "- Entered temp dir: "
    pwd

    # Download
    fname=`basename "$NODEJS"`
    if [ -f "$fname" ]; then
        echo "- $fname already exists, not downloading"
    else
        echo "- Downloading $NODEJS"
        wget "$NODEJS" || (echo "ERROR: download failed"; exit 2)
    fi

    echo "- Extracting"
    tar -xvzf "$fname" || (echo "ERROR: tar failed"; exit 3)
    cd `basename "$fname" .tar.gz` || (echo "ERROR: entering source directory failed"; exit 4)

    echo "- Configure"
    ./configure --prefix="$VIRTUAL_ENV" || (echo "ERROR: configure failed"; exit 5)

    echo "- Make"
    make || (echo "ERROR: build failed"; exit 6)

    echo "- Install "
    make install || (echo "ERROR: install failed"; exit 7)
fi

echo
echo "2) Installing npm"
echo
# Check npm is exists or not
which npm>/dev/null 2>/dev/null
if [ $? -eq 0 ]; then
    echo "The npm is installed."
else
    curl http://npmjs.org/install.sh | sh || (echo "ERROR: install failed"; exit 7)
fi


echo
echo "3) Installing lessc with npm"
echo
which lessc>/dev/null 2>/dev/null
if [ $? -eq 0 ]; then
    echo "The lessc is installed."
else
    npm install less -g || (echo "ERROR: lessc install failed"; exit 8)
fi


echo
echo "4) Installing uglifyjs with npm"
echo
which uglifyjs>/dev/null 2>/dev/null
if [ $? -eq 0 ]; then
    echo "The uglifyjs is installed."
else
    npm install uglify-js -g || (echo "ERROR: uglifyjs install failed"; exit 8)
fi

echo "Congratulations! The node is now installed and configured in your virtualenv"
