scripts.jquery:
    contents:
        - http://code.jquery.com/jquery-1.8.1.js

scripts.bootstrap:
    contents:
        - assets/bootstrap/js/bootstrap-alert.js
        - assets/bootstrap/js/bootstrap-button.js
        - assets/bootstrap/js/bootstrap-affix.js
        - assets/bootstrap/js/bootstrap-alert.js
        - assets/bootstrap/js/bootstrap-button.js
        - assets/bootstrap/js/bootstrap-carousel.js
        - assets/bootstrap/js/bootstrap-collapse.js
        - assets/bootstrap/js/bootstrap-dropdown.js
        - assets/bootstrap/js/bootstrap-modal.js
        - assets/bootstrap/js/bootstrap-tooltip.js
        - assets/bootstrap/js/bootstrap-popover.js
        - assets/bootstrap/js/bootstrap-scrollspy.js
        - assets/bootstrap/js/bootstrap-tab.js
        - assets/bootstrap/js/bootstrap-transition.js
        - assets/bootstrap/js/bootstrap-typeahead.js

less.bootstrap:
    filters: less
    contents:
        - assets/bootstrap/less/bootstrap.less


scripts.public:
    filters: uglifyjs
    output: app_public.min.js
    contents:
        - scripts.jquery
        - scripts.bootstrap

stylesheets.public:
    filters: cssmin
    output: app_public.min.css
    contents:
        - less.bootstrap
